# Generated by Django 4.0.3 on 2022-03-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='profile_image',
        ),
    ]
